[package]
name = "phpm-lock"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "composer.json and composer.lock reading, version normalisation and installed metadata"
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
indexmap = { workspace = true }
phpm-php = { path = "../phpm-php" }
regex = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
phpm-testkit = { path = "../phpm-testkit" }
proptest = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
