[files]
extend-exclude = ["fixtures/", "**/snapshots/", "*.snap", "Cargo.lock", "crates/*/tests/golden/", "crates/*/tests/data/", "crates/*/composer/*.php"]

[default.extend-words]
psr = "psr"
IST = "IST"
