sonar.organization=speedsharmaai
sonar.projectKey=speedsharmaai_phpm
sonar.projectName=phpm
sonar.sources=crates
sonar.exclusions=**/tests/**,crates/phpm-testkit/**
sonar.tests=crates
sonar.test.inclusions=**/tests/**
sonar.rust.lcov.reportPaths=lcov.info
sonar.rust.clippyReport.reportPaths=clippy.json
sonar.qualitygate.wait=true
