<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Z\\' => array($vendorDir . '/z/Mixed/src'),
    'Tests\\' => array($baseDir . '/tests'),
    'E\\' => array('phar://' . $vendorDir . '/e/phar/lib.phar/src'),
    'D\\' => array($vendorDir . '/d/dev/src'),
    'App\\' => array($baseDir . '/app', $baseDir . '/app-dev'),
    'A\\' => array($vendorDir . '/a/lib/src', $vendorDir . '/a/lib/more'),
);
