<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0123456789abcdef0123456789abcdef
{
    public static $files = array (
        '37b18b411a4d4b157195d85c6abbbdc3' => __DIR__ . '/..' . '/a/lib/boot.php',
        '4ea335c044a8c4e52ed7538afb722605' => 'phar://' . __DIR__ . '/..' . '/e/phar/lib.phar/f.php',
        '9a7b473edee907077ce728feee93c9a9' => __DIR__ . '/../..' . '/helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'Z' =>
        array (
            'Z\\' => 2,
        ),
        'T' =>
        array (
            'Tests\\' => 6,
        ),
        'E' =>
        array (
            'E\\' => 2,
        ),
        'D' =>
        array (
            'D\\' => 2,
        ),
        'A' =>
        array (
            'App\\' => 4,
            'A\\' => 2,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Z\\' =>
        array (
            0 => __DIR__ . '/..' . '/z/Mixed/src',
        ),
        'Tests\\' =>
        array (
            0 => __DIR__ . '/../..' . '/tests',
        ),
        'E\\' =>
        array (
            0 => 'phar://' . __DIR__ . '/..' . '/e/phar/lib.phar/src',
        ),
        'D\\' =>
        array (
            0 => __DIR__ . '/..' . '/d/dev/src',
        ),
        'App\\' =>
        array (
            0 => __DIR__ . '/../..' . '/app',
            1 => __DIR__ . '/../..' . '/app-dev',
        ),
        'A\\' =>
        array (
            0 => __DIR__ . '/..' . '/a/lib/src',
            1 => __DIR__ . '/..' . '/a/lib/more',
        ),
    );

    public static $prefixesPsr0 = array (
        'Z' =>
        array (
            'Z_' =>
            array (
                0 => __DIR__ . '/..' . '/z/Mixed/lib',
            ),
        ),
        'O' =>
        array (
            'Old_' =>
            array (
                0 => __DIR__ . '/..' . '/b/old',
            ),
        ),
    );

    public static $fallbackDirsPsr0 = array (
        0 => __DIR__ . '/../..' . '/legacy',
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0123456789abcdef0123456789abcdef::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0123456789abcdef0123456789abcdef::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit0123456789abcdef0123456789abcdef::$prefixesPsr0;
            $loader->fallbackDirsPsr0 = ComposerStaticInit0123456789abcdef0123456789abcdef::$fallbackDirsPsr0;
            $loader->classMap = ComposerStaticInit0123456789abcdef0123456789abcdef::$classMap;

        }, null, ClassLoader::class);
    }
}
