<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Z_' => array($vendorDir . '/z/Mixed/lib'),
    'Old_' => array($vendorDir . '/b/old'),
    '' => array($baseDir . '/legacy'),
);
