[package]
name = "phpm"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "An extremely fast, Composer-compatible PHP installer"
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[package.metadata.dist]
dist = true

[dependencies]
clap = { version = "4.6.6", default-features = false, features = ["derive", "error-context", "help", "std", "usage"] }
md5 = { workspace = true }
phpm-autoload = { path = "../phpm-autoload" }
phpm-lock = { path = "../phpm-lock" }
phpm-php = { path = "../phpm-php" }
phpm-store = { path = "../phpm-store" }
serde_json = { workspace = true }
sha2 = "0.11.0"
tokio = { version = "1.53.0", features = ["rt"] }
twox-hash = { workspace = true }

[dev-dependencies]
phpm-diffvendor = { path = "../phpm-diffvendor" }
tempfile = { workspace = true }
zip = { version = "8.6.0", default-features = false, features = ["deflate-flate2-zlib-rs"] }

[lints]
workspace = true
